name: AutoBuild
on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: my_download_server
  VERSION: latest
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build
        run: docker build ./Docker/ --file Dockerfile --tag $IMAGE_NAME:$VERSION
      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u libra146 --password-stdin
      - name: Push Docker image
        run: |
          IMAGE_ID=finalnarcissus/$IMAGE_NAME
          docker push finalnarcissus/$IMAGE_NAME:$VERSION
